/**
 * main
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ResultDataStat {
    id?: number;
    result_id?: number;
    word?: string;
    sysh?: number;
    glag?: number;
    nar?: number;
    soyz?: number;
    predlog?: number;
    pril?: number;
    prich?: number;
    deepr?: number;
    chisl?: number;
    mest?: number;
    morf_undefined?: number;
    synt_undefined?: number;
    not_set?: number;
    opredel?: number;
    obstoyt?: number;
    double?: number;
    underline?: number;
    dopol?: number;
    summary?: number;
}
