/**
 * Security API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The properties that are shared amongst all versions of the User model.
 */
export interface UserCommon { 
    id?: number;
    email?: string;
    role?: number;
    status?: number;
    access_token?: string;
    password_hash?: string;
    password_reset_token?: string;
    created_at?: string;
    updated_at?: string;
    created_by?: number;
    updated_by?: number;
    organisation_id?: number;
}
